### ISSUE TITLE
Include LICENSE.txt in release artifacts

### ISSUE THREAD

**Issue by psztrnk** [themotleyfool/Klondike#102]
Hi,

are previous versions of Klondike also available under the Apache License 2.0? Unfortunately the LICENSE.txt has been added only to the master branch (@2570ced), previous releases contain no applicable license information.

Thanks,
a

**Comment by chriseldredge** [comment]
Since the master branch is default and you see the file when coming to the project page on github, I interpret that as meaning it applies to all of the branches and tags, despite having been added after the fact.

I'm going to repurpose this issue to change the build process so that the license file is included in the distribution zip files.

**Comment by chriseldredge** [comment]
49968b0992a51b6154aaabba105ac63d06c0637d copies license and copyright into dist zip file during appveyor builds.
