### ISSUE TITLE
dnu restore does not redirect to correct OData path

### ISSUE THREAD

**Issue by xtheary** [themotleyfool/Klondike#108]
We have klondike setup as our nuget server and somebody reported that he couldn't restore his package , he got this error:
"Ignoring NuGet v3 feed http:/x.x.x/api, which doesn't provide PackageBaseAddress resource.". 
He had this using Visual Studio 2015 with asp.net 5
So before I start investigating I would like to know if this behaviour is normal and not supported.

Thanks

**Comment by chriseldredge** [comment]
That's correct. Klondike does not support NuGet v3 Feeds.

I'm not sure if there is any reference documentation on how to implement the feed and it looks like a major undertaking to me. I have no plans to implement support at this time.

**Comment by scabana** [comment]
Hi, 

To add a little information to this, it's directly related to asp.net 5/dnx projects using dnu restore. Their implementation ([here](https://github.com/aspnet/dnx/blob/219871c6063d00f8297eeafe93266f1048f59a45/src/Microsoft.Dnx.Tooling/Utils/PackageSourceUtils.cs)) tries to detect v3 feeds (method `DetectNuGetV3`). The problem seems to be that when you send a GET to the nuget.com feed without a Accept header, it returns xml by default (and then they revert back to v2 feeds). Klondike doesn't have the same behavior, it will return json by default which they try to parse and end up saying something like: it's a bad v3 feed. I agree that it's a poor implementation for detecting if it's a v3 feed.

**Comment by chriseldredge** [comment]
Wow, and [this line](https://github.com/aspnet/dnx/blob/08cf2d3586472267ab3dbb47aa93eb8cfdc2fe33/src/Microsoft.Dnx.Tooling/Restore/NuGet/NuGetv3Feed.cs#L91) seems like maybe not the best approach.

So as a result dnx projects refuse to use Klondike at all? It doesn't fall back to using the V2 feed?

**Comment by scabana** [comment]
Well, not with what I tried. I could maybe open an issue on there... kind of sad that there doesn't seem to be a version query in the nuget feed api :cry:

**Comment by lukeskinner** [comment]
I think the error is because the endpoint being used is incorrect in your nuget configuration. In the error message it shows the URL you're using as```http:/x.x.x/api``` when it should be ```http:/x.x.x/api/v2```. 

I managed to replicate this by following the 'Running the samples' section the [asp.net home project](https://github.com/aspnet/home#upgrading-dnvm-or-running-without-visual-studio).

To test this I added the Klondike feed to my NuGet.Config  (using klondike build [115](https://ci.appveyor.com/project/chriseldredge/klondike/build/115)):
```
<add key="testfeed" value="http://localhost:8082/api/v2" />
```

When I ran ```dnu restore``` on the asp.net samples folder it appears to work. It fails about a missing package but that's expected as the feed I'm using is empty.

![apiv2](https://cloud.githubusercontent.com/assets/7475696/9509085/9a3c4508-4c53-11e5-964c-7b4eec753426.PNG)

Next I tried changing the feed in my NuGet.config to (without the ```/v2```):
```
<add key="testfeed" value="http://localhost:8082/api" />
```
![api](https://cloud.githubusercontent.com/assets/7475696/9509182/7f79b808-4c54-11e5-99da-a85d2da3585d.PNG)

This then produces the same `Ignoring NuGet v3 feed http://localhost:8082/api, which doesn't provide PackageBaseAddress resource.` error message.

**Comment by scabana** [comment]
Nice work @lukeskinner, I'll validate that tomorrow morning and spread the intel! Thanks a lot.

**Comment by chriseldredge** [comment]
That makes sense. Klondike uses the User-Agent header to redirect the NuGet client to the correct API path for OData (which is actually `/api/odata/` for Klondike). DNX probably is using a different user-agent so the redirect is not working.

**Comment by chriseldredge** [comment]
Filed an issue with dnx project: https://github.com/aspnet/dnx/issues/2587

**Comment by chriseldredge** [comment]
Couple of tweaks in the latest build should allow Klondike to work better with DNX.

https://ci.appveyor.com/project/chriseldredge/klondike/build/119/artifacts

* UI instructs users to point their clients to `/api/odata`
* Fix for DNX requiring atom+xml response but not asking for it in Accept header
