### ISSUE TITLE
Using Klondike as a mirror will miss updates

### ISSUE THREAD

**Issue by hvanbakel** [themotleyfool/Klondike#109]
Assuming I have a nuget feed mirrored. If I want to get the latest version of a package I'm consistently seeing the last downloaded version rather than the newest version. 

Strangely this url:
`http://localhost/api/v2/package-versions/packagename`
returns all versions. Let's assume 1.0.0 and 1.0.1, but only 1.0.0 is donwloaded
Then, when I hit this url:
`http://localhost/api/packages?query=packagename&offset=0&count=20&originFilter=Any&sort=Score&order=Ascending`
I'm only getting 1.0.0 back, and not 1.0.1 even though apparently klondike was able to figure out that this 1.0.1 version existed.

**Comment by chriseldredge** [comment]
This may be confusing, but it is by design.

The intended workflow is that developers will use nuget.org or their other upstream feeds when installing and upgrading packages in Visual Studio, then when a CI build kicks off it would restore packages using Klondike. In this way Klondike will mirror packages during restore so that later if nuget.org is unavailable the build will still succeed.

Klondike offers package versions in the tab-completion endpoint so that users can see new packages when running Update-Package or Install-Package against Klondike. However, as you noticed the operations that search or find upgrades do not go out to mirror origins.

**Comment by hvanbakel** [comment]
Agreed, but what is the trigger for klondike to cache a package in that case? A call from package restore?

**Comment by hvanbakel** [comment]
And in addition to that, I'm seeing 2+ seconds for a cache miss to return a 404? Is that misconfiguration or is that just related to the request sent to the mirror?

**Comment by chriseldredge** [comment]
Do you have an example URL that is taking 2+ seconds?

You could try disabling the mirroring and see how that affects latency.

**Comment by hvanbakel** [comment]
Disabling mirroring results in a response of 0.023s so the check on the mirror was the problem.

Thanks!
