### ISSUE TITLE
500 error on symbol push

### ISSUE THREAD

**Issue by stormbringer766** [themotleyfool/Klondike#111]
When pushing a package that also has the symbols package, I get a 500 error. This was working fine up to a few days ago and no changes have been made. The package is updated fine. 

The issue seems to be around the 000Admin folder. I can read files from this folder using the API but if I try to make any changes, I get access denied errors. The IIS_IUSER has every permission but full control. If I try to give it full control, I get access denied errors.

I rebooted the server just in case it was just random file locks to no avail. 

I am using version 1.6.2 at the root of IIS. The symbols folder is outside of the IIS root.

**Comment by chriseldredge** [comment]
Klondike only creates directories and writes files into the Symbols folder. It does not set permissions or otherwise modify ACLs or other metadata on the filesystem.

**Comment by shoronda** [comment]
Closed#111

**Comment by brettveenstra** [comment]
Was encountering this when pushing to Klondike without the Debugging tools installed on the machine.  @chriseldredge - would you consider changing the behavior to ignore the .symbols.nupkg files and place an entry into the log instead of failing trying to process symbol files when debugging tools not installed?

**Comment by chriseldredge** [comment]
This should already be happening. See [SymbolsController.cs:56](https://github.com/themotleyfool/NuGet.Lucene/blob/bfb950418a939fab5183dcc0c0136a2e1e7e3df5/source/NuGet.Lucene.Web/Controllers/SymbolsController.cs#L56), [SymbolSource.cs:20](https://github.com/themotleyfool/NuGet.Lucene/blob/master/source/NuGet.Lucene.Web/Symbols/SymbolSource.cs#L20), and [SymbolTools.cs:19](https://github.com/themotleyfool/NuGet.Lucene/blob/master/source/NuGet.Lucene.Web/Symbols/SymbolTools.cs#L19).

**Comment by brettveenstra** [comment]
Thanks for the reply --- re:SymbolsController.cs:56 

how about

```
                  return Request.CreateErrorResponse(HttpStatusCode.NoContent,
                    "Windows Debugging Tools are not configured - skipping.");

```

that should return `2XX` code instead of `5XX` ... that should let the `push` happen without failure right?

**Comment by chriseldredge** [comment]
This issue is concerning a 500 Internal Server Error that appears to have a root cause related to file system permissions in the symbols directory where Klondike attempts to store symbol packages.

The issue you are describing appears to be different from that. If the tools are not configured, the client should be encountering an HTTP 501 Not Implemented response. That behavior could be changed, but to what end? What benefit is there to allowing the client to silently fail instead of making it clear that the action being invoked has no effect?

**Comment by brettveenstra** [comment]
In a CI/CD setting, the benefit is the pipeline doesn’t break when the PDBs aren’t accepted on a push.

If debugging tools aren’t installed, why do you consider that an error condition?  How would the client necessarily know and why should that be a critical failure?
