### ISSUE TITLE
Nuget push prompts for username/pwd

### ISSUE THREAD

**Issue by deepaktj** [themotleyfool/Klondike#115]
Hi,

I setup klondike to run on a remote server as a self hosted service.  When I try to push a package onto this repo I keep getting prompted for username/password again and again without any error message. Could you let me know what is incorrect with the way I setup or published.

Klondike-Setup

C:\Program Files (x86)\Klondike-Nuget\Nuget-Klondike\bin>Klondike.SelfHost.exe -
-url=http://SLGDSM020002114:90
Running interactively
2015-10-06 09:34:49,072 [1] INFO  Klondike.SelfHost.KlondikeService - Using Serv
erFactory Nowin
2015-10-06 09:34:49,580 [1] INFO  NuGet.Lucene.LucenePackageRepository - Refresh
ing index. Package count: 0
2015-10-06 09:34:54,353 [1] INFO  Klondike.SelfHost.KlondikeService - Listening
for HTTP requests on address(es): http://SLGDSM020002114:90
Press <enter> to stop.

Nuget push

C:\\src>.nuget\nuget.exe push ..\testpack.nupkg -Source http://SLGDSM020002114:90 
Pushing testpack to 'http://SLGDSM020002114:90'...
Please provide credentials for: http://slgdsm020002114:90/api/odata/
UserName: <username>
Password: *********
Please provide credentials for: http://slgdsm020002114:90/api/odata/
UserName: Password: ^C

**Comment by chriseldredge** [comment]
Are you expecting to be able to push packages without needing to authenticate? If that is the case you can change the `allowAnonymousPackageChanges ` key in [Settings.config](https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.WebHost/Settings.config#L21).

Otherwise, you can either use the `--enableIntegratedWindowsAuthentication` flag on the command line to enable Windows Authentication.
