### ISSUE TITLE
Added accounts do not appear on Account Overview

### ISSUE THREAD

**Issue by Stift** [themotleyfool/Klondike#129]
I just freshly installed the new Klondike 2.0 and wanted to add accounts. I can create an account but this does not show up under "Manage Accounts".

**Comment by mkoertgen** [comment]
Yep, for me thoo

**Comment by brettveenstra** [comment]
Same here but found that new User appears in Chrome, not in IE...

**Comment by chriseldredge** [comment]
Works for me on Safari, Chrome and Firefox on OS X. Does reloading the page help?

**Comment by Stift** [comment]
Reload does not help. Maybe I'll try to debug this issue.
My setup is IE 11. FF works fine.

**Comment by Ashtonian** [comment]
Can confirm - issue with IE. I'm on IE 10 and the console eventually prints "SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally"

**Comment by Ashtonian** [comment]
I ended up running klondike under IIS and it fixed the problem even if IE.

**Comment by chriseldredge** [comment]
This turned out to be an http cache-control issue. I'm not sure how Klondike has made it this far without noticing this problem :)

https://github.com/themotleyfool/NuGet.Lucene/commit/7b870c36bc100ffeebfeaf371f988601d2edb967 adds cache-control header with max-age=0 to prevent IE from caching previous responses to the API.

This fix will be included in the next release of Klondike.

**Comment by chriseldredge** [comment]
Released in v2.2.1

https://github.com/themotleyfool/Klondike/releases/tag/v2.1.1

**Comment by Ashtonian** [comment]
Thanks!!
