### ISSUE TITLE
Package advanced search error

### ISSUE THREAD

**Issue by ryager** [themotleyfool/Klondike#137]
While trying out the advanced search feature for packages I encountered the following error:
![image](https://cloud.githubusercontent.com/assets/8608137/13366120/18b6c528-dc8e-11e5-9e4d-3fc88e692c38.png)

Since there was no documentation I wasn't sure what was expected, but I certainly wasn't expecting the cryptic message that implies I needed to provide a value to search for.

**Comment by chriseldredge** [comment]
This is an ugly integration point between Klondike and the underlying Lucene.Net library that powers search. Since the query includes a colon, Klondike assumes advanced (Lucene query syntax) is being used and tries to pass the query directly into Lucene.Net for parsing. The error message comes directly from Lucene.Net. It isn't user friendly.

I don't think there is an easy fix here. In Lucene land over in Java land, Solr includes a DisMax and ExtendedDisMax parser that are supposed to always work and never generate error. Practice and theory are not the same in my experience (example: using a boolean keyword operator in uppercase like `NOT`,`OR`, `AND`  without quoting it results in an error).

Finally, this particular error is ultimately due to the space between the colon and the keyword being searched (`false`). But again, Klondike has no way of detecting this or translating the error message that comes out of Lucene.Net into something more human friendly.
