### ISSUE TITLE
How can I launch Klondike in non-interactive mode?

### ISSUE THREAD

**Issue by fandrei** [themotleyfool/Klondike#145]
I can't find any option for this in the latest release.

**Comment by pdfforge** [comment]
Hi,

I assume that you are using the selfhost.exe, is that right? In that case, there is the manual page which shows how to start it as a service:
https://github.com/themotleyfool/Klondike/blob/master/src/Klondike.SelfHost/README.md

Philip

**Comment by fandrei** [comment]
@pdfforge, is it possible to launch it as a normal process, but without interactive interface?

**Comment by pdfforge** [comment]
I don't know what happens when you set interactive to false in the settings.config. Maybe it will work as you expect, but maybe it just terminates immediately. It's probably worth trying. Otherwise, creating a service is a matter of seconds, so you can easily set it up and remove it when you are done.

**Comment by fandrei** [comment]
@pdfforge, it's doing nothing - at least in the last available release.
Ok thanks, I can do it this way.
