### ISSUE TITLE
Authentication to Web UI fails with API Key (Release 2.0.0)

### ISSUE THREAD

**Issue by MatthewHartstonge** [themotleyfool/Klondike#149]
Hey Team,

Been trying to hack into the admin account, but I can't seem to gain access. 
Currently I'm working on creating a docker image for Klondike, and due to serving on a Linux Server, there is no GUI, so no way to access it through 127.0.0.1. 
I have tried using a putty tunnel to the server mapping remote 127.0.0.1:80 to my own 127.0.0.1:80 to no avail.
I've also tried editing the Settings.config and setting a key, but I don't think this is the same as the web auth logon.

So I guess, from a containerized point of view, what would be the best way to go about creating a base administrative user that is able to login remotely?

As such, I'm keen to help out with a Dockerfile to help ease Linux deployment! 
I've already got it working in a container, (you're mono deployment made it very easy to make the image super slim as well :D) just obviously need to access the frontend admin functionality on first kick remotely not locally..

**Comment by chriseldredge** [comment]
It's true you can't log in on the browser using an api key, and the self-hosted Klondike doesn't really support external authentication on mono as far as I know. On Windows, the `--enableIntegratedWindowsAuthentication` switch would enable it.

You could try `--enableIntegratedWindowsAuthentication --serverFactory=Microsoft.Owin.Host.HttpListener` on mono, but I'll be surprised if it works.

As a work-around, you can set a fixed api key in Settings.config and use that from curl or other http clients to invoke administrative actions:

    curl -H 'X-NuGet-ApiKey: super-secret-key' https://klondike.foolhq.com/api/indexing/synchronize -d 'mode=Incremental'

You can see all the API actions by browsing `~/api`.

As far as making it easier to bootstrap in Docker, the Klondike UI should probably let you authenticate by api key, since it ends up using this key after authentication to invoke various operations.

Another option would be to add a configuration setting that allows additional network addresses to be treated as "local" and automatically authenticate as `LocalAdministrator`.

**Comment by MatthewHartstonge** [comment]
I've managed to work around this, as mentioned, by creating a user curl'ing the API. As for logging into the web interface on the 2.0.0 release, I am still not able to log on with the API Key assigned - Yet sending NuGet packages e.t.c. is all happy with the -ApiKey switch with the newly created 'admin' user.
Is the UI password != apikey for logging on?

As a workaround, I've flicked the switch on 'allowAnonymousPackageChanges' to enable UI based management of packages.
