### ISSUE TITLE
Klondike exits immediately when running under a docker container via mono 

### ISSUE THREAD

**Issue by watermelonpizza** [themotleyfool/Klondike#156]
When I tried to run klondike under mono using docker, the application starts and exits immediately. 
Used this as the docker container https://hub.docker.com/r/athieriot/docker-klondike/~/dockerfile/

(Although I think it is broken, if you run the mono comment with the full path it runs)

**Comment by HackedByChinese** [comment]
You need to install `mono-4.0-service` package and use `mono-service` to host with the `--no-daemon` flag.

```
FROM mono:4.2

RUN apt-get update && apt-get install -y \
    mono-4.0-service \
    wget \
    unzip && \
    rm -rf /var/cache/apt/*

WORKDIR /app

RUN curl -s https://api.github.com/repos/themotleyfool/Klondike/releases | \
    grep browser_download_url | head -n 1 | cut -d '"' -f 4 | xargs wget && \
    unzip *.zip

COPY Settings.config /app/Settings.config

WORKDIR /app/bin

CMD ["mono-service", "Klondike.SelfHost.exe", "--no-daemon"]

EXPOSE 8080
```

I published an image. `docker pull officepracticum/klondike`

**Comment by chriseldredge** [comment]
Docker support is outside the scope of this project. Klondike's log file, or stderr / stdout, will likely give you a hint about what the problem is. Note in particular that the `bin` directory needs to be the current working directory for mono-service to work properly. See also https://github.com/themotleyfool/Klondike/tree/master/src/Klondike.SelfHost

**Comment by watermelonpizza** [comment]
Oh it's `mono-service` which was what I was missing! D'oh. Thanks @HackedByChinese! All works now.
