### ISSUE TITLE
Support for per-package security

### ISSUE THREAD

**Issue by georgiosd** [themotleyfool/Klondike#76]
Hi!

I've been crawling the web for a free nuget server that can have per-package security - the use case is an internal feed between separate departments, some of which shouldn't be able to see/download other departments' packages - to no avail. 

I came across your project and from what I can see it doesn't support this either but I was thinking I could perhaps send you a pull request for it.

First, are you interested in this feature? And second, how would you go about implementing it?

Thanks
Georgios

**Comment by chriseldredge** [comment]
Klondike currently only supports role-based authorization, generally backed by security group membership in active directory. Authentication and authorization are configured by Web.config and Settings.config.

Have you considered deploying separate instances of Klondike, one for each department or organizational unit that requires custom settings?

Per-package access control would be feasible to implement in the current architecture. If I was going to try implementing this, I would probably create a new OWIN middleware that checks the current user for membership in a list of pre-defined roles, and use that to build a filter query that gets included on every query.

Additional consideration is necessary to explore how users would specify an access-control-list for a given package and how that would be translated into queryable metadata. For example, using security identifiers (SID) instead of simple strings may be necessary in the case that a security group is renamed or moved from one domain to another.

Since this is the first request I've seen for such functionality, and since it would complicate the code considerably, I would be hesitant to include it in NuGet.Lucene and Klondike. But if you find that having a separate instance of Klondike for each security configuration is not feasible, and the implementation is relatively clean, I would consider merging it.

**Comment by georgiosd** [comment]
Thanks for the response.

By "OWIN middleware", you mean a sort of proxy that will rewrite queries and pass them to Klondike? If so, that seems like a good compromise - any pointers to get me started on what I'd need to do with the nuget URL passed in?

Re the ACL, I was thinking of something simple such as regexps on packages mapping to user groups. Thoughts?

**Comment by chriseldredge** [comment]
As a start, I would add a middleware class to the [NuGet.Lucene.Web.Middleware](https://github.com/themotleyfool/NuGet.Lucene/tree/master/source/NuGet.Lucene.Web/Middleware) namespace that checks the current user for membership in some pre-defined list of roles, then binds that list to Autofac so that LucenePackageRepository has access to the list in order to filter results. I would also consider configuring LucenePackageRepository in Autofac to be bound to the OWIN request, so that each executing request can have the right list of ACLs for the current user.

When a package is being added to the index in LucenPackageRepository, this is where you would include a list of one or more roles that are allowed to see a package.

**Comment by georgiosd** [comment]
Hm.... reviewing the work necessary, I think I'm just gonna make a proxy to Nuget.Server that will knock off results based on a regex. Will keep you posted.

**Comment by chriseldredge** [comment]
Ok, happy coding :)
