### ISSUE TITLE
Use klondike as non-root web application

### ISSUE THREAD

**Issue by pkorsukov** [themotleyfool/Klondike#77]
I have started testing a new beta release and it seems the virtual folder deployment are not supported.
In the recent builds there are no ability to deploy Klondike in the folder under the root website. I was able to change the base tag to point to the right location but all links to /api and auth are not working.

**Comment by chriseldredge** [comment]
It looks like the API metadata served by `~/api` is not returning correct API paths in this configuration.

**Comment by chriseldredge** [comment]
There was a bug in the WebHost startup code that prevented the correct virtual path root from being used. This is fixed in build 89.

https://ci.appveyor.com/project/chriseldredge/klondike/build/89/artifacts

Please note: the Ember admin app is built in a way that requires changes in 2 places when using a path other than `/`:

* Change the `<base>` tag in index.html
* Change the `apiUrl` value in assets/klondike.js (all the way at the bottom)

Also note that NuGet clients will not work correctly for certain operations like tab completion. The client uses hard-coded paths for this and only works when the app is deployed at `/`.

**Comment by pkorsukov** [comment]
Thank you. It seems to be working. 
But it would be great to do not change assets/klondike.js. Is it possible to check value in base tag from JS?

**Comment by chriseldredge** [comment]
Perhaps. The Ember app has a separate config setting that allows an arbitrary API url to be used. This can be useful while developing Klondike and wanting to point somewhere else for test data. Perhaps this setting could be left empty or null by default which could trigger the initialization to compute the URL using the `base` tag.
